### ISSUE TITLE
How to execute command with args after the test finishes

### ISSUE THREAD

**Issue by CyberMew** [typekpb/wtfc#3] opened 2018-03-05 07:00 UTC
So I'm waiting for my mongo db to startup at dbip:dbport, and once done I need it to run a command to start my server. I was thinking of something like `./wtfc.sh dbip:port runmyserverscript argstomyscripthere` Is this possible with this script or am I mistaken?

**Comment by typekpb** [comment] 2018-03-05 09:28
@CyberMew well, I'd run it like this:

    ./wtfc.sh -T 0 nc -z <dbip> <dbport>
    <runmyserverscript> <argstomyscripthere>

So it should wait for the your mongo to be up first (without timeout), once it's up, it'll run whatever you need.

**Comment by CyberMew** [comment] 2018-03-12 07:21
> TestingOnMyMacTerminal:test CyberMew$ ./wtfc.sh -T 0 nc -z localhost 27017 echo "aa"
> wtfc.sh: waiting without a timeout for nc -z localhost 27017 echo aa

Starting up an instance of mongodb..

> wtfc.sh: nc -z localhost 27017 echo aa finished with expected status 0 after 10 seconds

I got the above output following your instructions, but echo wasn't executed.

**Comment by typekpb** [comment] 2018-03-14 16:22
the problem is, that it are the 2 separate commands, the 1.st one is the `./wtfc... ` and the `echo "aa"` is the 2.nd only only. So you should not try to run them together (as one command)

**Comment by CyberMew** [comment] 2018-03-16 03:45
Ah I see.. so there is no way for this to wait for a service to be ready and then get it do something?

**Comment by typekpb** [comment] 2018-04-23 11:10
@CyberMew unless you run the 1.st command in the background, it's an implicit way of running things in the shell => in sequence

Closing, as solution seems to be clarified. Feel free to reopen if more discussion is needed.

**Closed as completed by typekpb** 2018-04-23 11:10 UTC
